### ISSUE TITLE
Requesting a type should return a named type (if there is only one)

### ISSUE THREAD

**Issue by glibsm** [uber-go/dig#112]
Lets say we have a type `A:foo` in the graph.

Currently, requesting for type `A` will result in an error, since unique identification for an object is type+key.

We can make this experience a lot better. The high-level behavior can be like this:

- Requesting for `A` will return `A:foo`, if there is only one in the graph
- Requesting for `A` when `A:foo` and `A:bar` are provided -> error
- Obviously requesting for `A:foo` will never return `A:bar`, even if that's the only object provided

This would get tricky if `Invoke` is called on type `A` in between `Provide` of  `A:foo` and `A:bar`

**Comment by akshayjshah** [comment]
The current behavior sounds like the least surprising to me - it ensures that applications won't suddenly break if modules provide additional objects into the graph.

Have we encountered concrete use cases that require this behavior?

**Comment by glibsm** [comment]
No, I do not think there are concrete cases for this.

@abhinav suggested that module authors would be able to pre-tag objects if they chose to, while still solving the use case of "just give me an object of type X".

**Comment by akshayjshah** [comment]
Cool, makes sense. Maybe just let this issue hang out until we're more confident we need/don't need it?

**Comment by bayesianmind** [comment]
@abhinav and I were talking about this today. Automatically giving a named client if there is exactly one in the container is super convenient if we're naming the outputs from the yarpc generated fx client modules. It allows us to always name the output clients with routing name without forcing all users to use dig.In structs. This is important for those services that have multiple clients with the same routing key. I believe YARPC team knows of several examples of such services (and Catalyst for sure wants multiple clients w/ different names too)
Another bonus of dig having this feature is that when we introduce named outputs to the autogenerated FX client modules it won't be a breaking change.

**Comment by abhinav** [comment]
To reiterate:

We want to support multiple clients of the same type with different names
because we know for a fact that service authors are doing this to
separately route to their staging machines.

The idea is that we will generate a `dig.Out` struct using reflection which
`Provide`s a client with the same name as the routing name. So calling
`catalystfx.Client("staging")` will generate a constructor equivalent to,

    func(d *yarpc.Dispatcher) struct {
      dig.Out
      
      Client catalystclient.Interface `name:"staging"`
    } {
      // ...
    }

See yarpc/yarpc-go#1200 for @bayesianmind's WIP diff implementing this.

This brings up a problem: Users now HAVE to use `dig.In` structs with
`name:"catalyst"` even if they have only a single client. They can't do what
they were doing before (`fx.Invoke(func(catalystclient.Interface) {..})`). If
we implement the feature proposed in this issue, they won't have to do that
for the common case where they have only a single client.

A bonus of this which I think is more important is that it gives us the
ability to add names to `dig.Out` fields after releasing a 1.0 of a library
without breaking anything. That is, if I release my fx-compatible module which
`Provide`s a `*zap.Logger`, and then later I decide that I want to give it the
name `root` because there are use cases where multiple `*zap.Logger`s are at
play, I can't quite do that without breaking all existing users--since they've
been depending on the unnamed `*zap.Logger` instance. If this feature was
implemented, I would be able to do that without breaking anyone.

**Comment by breerly** [comment]
+1 Great points Abg

**Comment by glibsm** [comment]
Included in the v1 milestone

**Comment by akshayjshah** [comment]
I completely buy the use case that @bayesianmind has pointed out, and agree that we don't want everyone to always use `fx.In` structs. However, I don't think that this is the best way to achieve that aim - implementing this feature will make seemingly innocuous changes break services.

Take the example above, with catalyst clients. As a service owner, I start with the output of `catalystfx.Client("production")` in the graph. I can now invoke a function that expects a `catalystclient.Interface` without providing a tag and get the production client. Everything is great so far.

Now I realize that I also need a staging client. By *adding* `catalystfx.Client("staging")` to the graph, I've suddenly *broken* my existing invoked function. I don't think that this is desirable - it's a bit confusing, and it makes cross-module pollution more of a problem (adding new modules to an application is more likely to break existing code).

Luckily, I think there are other ways to make named outbounds more convenient. For example, we can make `catalystfx.Client` return an unnamed client, as it does today. We can then add `catalystfx.NamedClient`, which lets you choose a named outbound and puts a tagged instance into the graph. `NamedClient` should also support an option to provide the same object without a name, so that it's the default client.

With more than one named outbound,

```
fx.Provide(
  catalystfx.NamedClient("catalyst-registry", catalystfx.Default),
  catalystfx.NamedClient("catalyst-registry-staging"),
)
```
lets us both support unnamed parameters and have multiple named instances in the graph.

**Comment by glibsm** [comment]
I'm going to drop this from the v1 milestone (since it doesn't actually affect any 1.0 APIs), it's a behavior change that we could consider introducing in 1.1.

Based on the last comment it sounds like we could do some prototyping to get around the problem in other ways.

**Comment by abhinav** [comment]
I don't think we can make this change anymore since it would constitute as behavior-breaking.

Closing.
