### ISSUE TITLE
Instantiate types directly

### ISSUE THREAD

**Issue by breerly** [uber-go/dig#17]
Currently DIG support providing types in 2 ways:

- Providing a constructor function to be executed in order to create type `Foo`
- Providing an already instantiated instance of type `Foo`

In addition to that, we should allow for the following common use-case:

Providing type `Foo` directly, so that DIG can instantiate it during resolve-time.

This would remove the need to define constructors like so:

```
func NewFoo(a,b Handler) *Foo {
  return &Foo(a: a, b: b)
}
```

Instead, one could pass Foo to DIG like so:

```
container.Provide(new(Foo))
```

Then, DIG will instantiate a struct of type `Foo`, treating the properties on `Foo` as it would the params in the constructor.

**Comment by glibsm** [comment]
What about "inject" functionality? What if I already have a constructed instance and I want to inject all the types that dig knows about. 

Is that also something we should consider sooner rather than later?

**Comment by akshayjshah** [comment]
Is this a pattern we want to encourage? To avoid standard Go constructors, it introduces a number of issues:

1. All struct fields that need initialization will need to be exported.
2. (1) implies that the types of most fields must be exported, or the GoDoc won't be useful.
3. For backwards compatibility, all future fields must have workable zero values.
4. It'll be difficult to require that users provide constructors instead of instances (see #74).

**Comment by breerly** [comment]
This isn't blocking 1.0, so in that case I'm going to close this. 

We can revisit later if we perceive it might be useful.
