### ISSUE TITLE
Adding the container itself inside of dependency graph

### ISSUE THREAD

**Issue by rssathe** [uber-go/dig#201]
Is there a mechanism to add the container itself as an argument when calling invoke or provide? If not that would be useful

As an example: 
```
err := c.Provide(initHandlers)

type Handlers struct {
	dig.Out

	Users    *UserGateway
	Comments *CommentGateway
	Posts    *PostGateway
}

func initHandlers(c *dig.Container, log *zap.Logger) Handlers {
	err := c.Provide(users.NewUserGateway)
	if err != nil {
		log.Fatal(err)
	}
        ...
}
```

**Comment by abhinav** [comment]
Hello! Yes, you can Provide the container to itself and consume it elsewhere.

```go
c := dig.New()
if err := c.Provide(func() *dig.Container { return c }); err != nil {
    // ..
}
```

That said, from a best practices point-of-view, it is not recommended that you
do this. Having access to the container anywhere near business logic makes it
easy to accidentally (or intentionally) rely on it for business logic. There
are a number of reasons to avoid that:

- It encourages reading/writing from/to an arbitrary bag of values instead of
  all objects explicitly defining their dependencies and outputs in their
  constructors. This also makes testing slightly harder.
- Dig relies on reflection for most of its functionality. This has a
  significant cost at runtime if made part of the hot path. (This overhead is
  negligible if done once at startup, especially for long-running processes.)
- None of the dig APIs are thread-safe. They assume that Provide, Invoke, etc.
  are all called from the same goroutine one-at-a-time.

**Comment by abhinav** [comment]
Resolving this. Feel free to re-open if you have more questions. Thanks!
