### ISSUE TITLE
How to properly close resources?

### ISSUE THREAD

**Issue by nkonev** [uber-go/dig#213]
How to properly close resources such as connection, file, ... etc?

**Comment by glibsm** [comment]
It's somewhat difficult to answer this question without seeing your particular usage of dig. In general, unless you're building another framework, you should be using https://github.com/uber-go/fx instead of dig directly. As opposed of just being a dependency injection container, it's a framework built around it which contains (amongst other things) start and stop hooks.

A typical Fx constructor for `SomeType` which needs to do some work on startup and shutdown would look like this:

```go
func New(lc fx.Lifecycle) (SomeType, error) {
	// do some initialization work...

	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			// do some work on application start (after graph resolution)
			return nil
		},
		OnStop: func(ctx context.Context) error {
			// do some work on application stop (like closing connections and files)
			return nil
		},
	})

	return SomeType{}, nil
}

```

**Comment by alameya** [comment]
> How to properly close resources such as connection, file, ... etc?

we with my friend build our own framework and have the same question last 2 weeks.
he even wanna to hardfork a project...
plz implement this params or context for community Q.Q

**Comment by abhinav** [comment]
@alameya That Lifecycle pattern is implemented and provided in [Fx][1], which
is built on top of Dig. We prefer for Dig to handle only the dependency
injection portion of this equation.

If you're building your own framework and can't use Fx, we recommend
replicating [Fx's Lifecycle pattern][2] or similar. 

[1]: https://github.com/uber-go/fx/
[2]: https://github.com/uber-go/fx/blob/master/internal/lifecycle/lifecycle.go

**Comment by tux21b** [comment]
Hi, I just stumbled upon dig and fx and I have similar concerns. A short demo project revealed that ``OnStop`` hooks will not be executed if there is an error during construction (before the start phase). Unfortunately, most resources (like your ``sql.DB`` example in the dig documentation) must be closed once the constructor succeeded.

So, it looks like I would have to provide a ``**sql.DB`` in the first place, call ``sql.Dial`` in an ``OnStart`` hook so that I can call ``db.Close`` during the ``OnStop`` hook. All other providers must not use ``*sql.DB`` in their constructors and must move all work to the ``OnStart`` hook as well since the database will be a nil-pointer until then. This means that I probably have to post-pone the construction of the other objects until the ``OnStart`` phase as well, which means that I have to return an uninitialized double pointer during the construction of the other objects as well. This becomes really tedious....

I might be missing something, but I do not see a way how someone can use this library in production. Please clarify :)

Most other frameworks (like Google's wire for example) provide an optional close mechanism for the constructed objects and I think this feature is mandatory in dep itself.

**Comment by Pourqavam** [comment]
For something like database, you can use defer container.Invoke(...) in main.
For example:
```
defer container.Invoke(func(db *gorm.DB) {
	db.Close()
	fmt.Println("db closed")
})
defer container.Invoke(func(c redis.Conn) {
	c.Close()
	fmt.Println("redis closed")
})
```
