### ISSUE TITLE
Please release dig.As

### ISSUE THREAD

**Issue by bithavoc** [uber-go/dig#238]
Hi. I'd like to use `dig.As` but it hasn't been released as per 1.7 series.

**Comment by abhinav** [comment]
Hi! There are some minor issues with the design of the API that we'd like to
address before releasing. These issues were pointed out in this comment
https://github.com/uber-go/dig/pull/235#pullrequestreview-219719941.

We haven't had a chance to address these yet because of other priorities but
we'll try to get to it soon.

Thanks!

**Comment by glibsm** [comment]
If you need to use it, or just want to try it right now, you can point your dependency manager specifically to the commit that merged it in.

Your feedback could also be important to get the feature through faster.
