### ISSUE TITLE
Named instances

### ISSUE THREAD

**Issue by glibsm** [uber-go/dig#30]
Assuming `dig` needs to support multiple instances of the same type in the graph, perhaps indentified by a string tag or something simiar.

This has a pretty large implication on what the `Provide` and `Resolve` functions are going to look like. 

I think the `Provide` is simpler and something along the lines of  `func (graph) Provide (interface{}, ...Option) {}` should be sufficient.

For example,

```go
c := dig.New()
var main, backup *DBConnection
c.Provide(main, dig.Named("master"))
c.Provide(backup, dig.Named("follower"))
```

The flip side if much harder, especially from a constructor perspective. Lets look at the following constructor:

```go
func BusinessLogic(l *zap.Logger, c *DBConnection) *Logic {
    // codez
}
```

How can a constructor like that specifically request a master database connection object?

**Comment by breerly** [comment]
There are 2 ways to accomplish this

## Using OOP

With regular 'ol OOP, the above can be solved with a factory func like so:

```go
func NewDbConn(config MyConfig) *DbConn {
  if config.Db.Master == true {
    return &DbMaster{}
  }
  return &DbFollower{}
}
```

In this way, you have 1 constructor responsible for creating the type. The constructor *relies* on all the deps it needs to to create the right type.

In this model, we would document "How to deal with multiple instances of the same type".

The benefit here is that less is more - we actually have everything we need right now.

## Using a container primitive

Providing this natively allows users to forgo the factory function, and do things like:

```go
c.ProvideNamed("myapp.db.master", NewMasterConn)
c.ProvideNamed("myapp.db.slave", NewSlaveConn)
c.Provide(NewBusinessLogic, dig.Named("myapp.db.master"))
```

In the above, `c.ProvideName` is an alternate registry entrypoint which:

> Don't infer the type name from the type, instead, use the type name I provide explicitly.

Then, when other types are provided, they can specify with an option `dig.Named`:

> Look up the "myapp.db.master" type, and then use that for `*DbConn` when instantiating

The benefit here is that you can easily register many types of the same instance, without having to create a factory function responsible for creating all those types.

This adds a good amount of complexity and API surface, and there are many times where a factory function is needed anyways (for example, when you need to take on deps in order to decide *which* instance to return).

I hope this is useful.

**Comment by breerly** [comment]
@glibsm note about "Using a container primitive" - 

I'm showing a kind of lazy version, where you provide a named hint, and all other params are determined using reflection (the current behavior). There are problems with this, and typically containers with support for named types make you specify *every* parameter.

**Comment by breerly** [comment]
In general, I think we should make a feature fight for its existence - if there isn't a pressing need now, lets see how far we can get with the factory func approach.

**Comment by madhuravi** [comment]
With named objects such as
c := dig.New()
var main, backup *DBConnection
c.Provide(main, dig.Named("master"))
c.Provide(backup, dig.Named("follower"))

I can fetch (resolve) master and follower wherever I want to in my code. Does the constructor function enable this? Looks like the it would create a new one every time I do a dig.Resolve?

**Comment by nathanjordan** [comment]
I'm looking to adopt this library for my team and cannot do so without some kind of named instances support.

**Comment by glibsm** [comment]
@nathanjordan the named instances topic comes up often when initially taking a look at dig (also why this issue is already open to discussion), however in many cases it can be solved by using a factory that can return multiple instances of the same type based on name, or some other attribute.

To help us understand the needs, could you describe your use case and how you see named instanced fit into it? Pseudocode also helps

**Comment by glibsm** [comment]
Going to close this discussion ticket and open an actionable issue to get named instances into dig - we now have a way to do it.

Will link the two together.
