### ISSUE TITLE
Don't recover panics

### ISSUE THREAD

**Issue by breerly** [uber-go/dig#57]
While it's true reflection-based code can panic quite abit - recoving in dig means *also* recovering panics located in user-land code - which is not desirable.

Thoughts? (continued discussion from #51)

**Comment by breerly** [comment]
cc @akshayjshah

**Comment by glibsm** [comment]
Initial thought: I *think* it's possible to move the recovery code around so that we don't enclose the `reflect.Call` to the constructor in the panic recovery. 

It's not a complete solution, because we can actually mess up the parameters to the `Call` itself, rather than what happens in the execution. I don't know if we want to do things like inspect the last lie in the panic stack to see where it came from

**Comment by akshayjshah** [comment]
Why not just return errors?

**Comment by glibsm** [comment]
@akshayjshah 

> Why not just return errors?

Can you clarify what you mean? We do return errors

**Comment by akshayjshah** [comment]
Sorry, missed this discussion earlier. I intended to convey this: I'd love it if we could treat all panics within our libraries as segfaults. This means that we *never* use panics as exceptions, and never need to recover our own panics.

This gets solved as part of #72.

**Comment by akshayjshah** [comment]
Fixed.
